### ISSUE TITLE
Possible improvements to analyzer

### ISSUE THREAD

**Issue by notpeter** [CppCXY/EmmyLuaAnalyzer#11]
I gave the new EmmyLuaAnalyzer a whirl and here's some things I found:

# Bugs

- [x] Hover state does not show class fields
    <img width="375" alt="image" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/c3ab6d5c-6e8e-46ef-9843-7c64d1bf63c0">

- [ ] "Read more" arrow always shows, even with subwindow is empty
    <img width="828" alt="Screenshot 2024-05-02 at 20 42 20" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/8ce7da89-2c11-4f95-951c-14f7e13bc93d">

- [x] `---@deprecated` does not appear in hover. Calls to deprecated methods should be ~striken()~.
    <img width="266" alt="Screenshot 2024-05-02 at 20 46 22" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/f0b9f330-88db-42f0-a597-c8ef37e589f5">

- [ ] Clicking EmmyLua in status bar results in "`emmy.stopServer` not found" error message.
    <img width="577" alt="Screenshot 2024-05-02 at 20 50 45" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/633c8d73-f846-4f51-8b6f-244e1bab73e7">

- [x] Putting an invalid path (e.g. `"fakedir"` into `workspace.library` in emmyrc.json caused crash on startup. If you change/add this mid-session EmmyLua becomes non-responsive (and stop is broken).
    <img width="1290" alt="Screenshot 2024-05-02 at 21 03 00" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/43900914-72dd-4074-87a0-2ed67b143404">

- [x] #12
    <img width="561" alt="image" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/3bc7a2ee-1a6b-46b4-8fdc-b4f4fc5c847f">
    <img width="641" alt="Screenshot 2024-05-02 at 21 17 09" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/c61e0133-8f7a-4211-be69-1f1793cc98c2">

- [ ] Completions for `---@` should should only be type annotation related `[@class,@param,@return,etc]`
    <img width="684" alt="Screenshot 2024-05-02 at 21 17 58" 
src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/19729092-f7df-4aea-86e6-09f8901add06">

- [x] #13
    <img width="546" alt="Screenshot 2024-05-02 at 21 21 09" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/7b2c322c-cf0b-48cd-8aa4-f2b8842377fa">

- [ ] Duplicate functions (with different params) inside a `---@meta` are not suggested as multiple options (first wins?)
   <img width="741" alt="Screenshot 2024-05-02 at 21 25 38" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/60d5e102-b76b-46ca-af0b-f1e0146fb867">

- [ ] Types on `...` are not properly checked and `...?` is displayed as`...` in function signatures.
    <img width="676" alt="Screenshot 2024-05-02 at 21 30 08" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/95445343-0bbe-4ac5-b9fd-0ec862083858">

- [x] Class field descriptions do not appear as part of extended suggestion, but are present in the hover window.
     <img width="773" alt="Screenshot 2024-05-02 at 21 47 37" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/7d8f6ff8-298b-4f50-93a4-4239e2c5fcd1">

- [x] #14
    <img width="435" alt="Screenshot 2024-05-02 at 21 50 39" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/332e50bc-f552-40c5-b621-604b70dd6be6">

- [ ] Assignments to optional returns (e.g. `string?` or `string|nil` do not preserve their nullability in types. This should be `_File?` or `_File?`.
    <img width="391" alt="Screenshot 2024-05-02 at 21 56 20" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/0e72949f-432c-438e-a3f3-dd81a9f5d122">

- [x] `workspace.library` in `.emmyrc.json` only works with relative paths. [0.6.15 changelog here](https://github.com/EmmyLua/VSCode-EmmyLua/blob/master/CHANGELOG_EN.md#0615) says:
    > Now all places where paths can be filled support relative paths, absolute paths, and `${workspaceFolder}` to represent the workspace, `~` to represent the user directory
    Tildes do not expanded properly (`~/proj` becomes `/proj`). Absolute paths are wrongly concatenated as paths under `workspaceFolder`. `${workspaceFolder}/../whatever` works as designed.

- [ ] Assignments should preserve transitive comment annotations.
    <img width="468" alt="Screenshot 2024-05-02 at 22 51 56" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/66875ba4-2bae-49d7-8533-57fcc4d66c6d">

- [x] Quote handling for `@alias` types is not right (duplicated double quotes): `""`.  Dunno if the EmmyLua types need to updated.  Here is how LuaLS defines them for reference.
    <img width="1159" alt="Screenshot 2024-05-02 at 23 02 12" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/8bf839d7-7f03-48dd-b894-6ac9e5a8d267">
    <img width="1168" alt="Screenshot 2024-05-02 at 23 07 28" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/e44ca61f-458e-47da-94fa-88bc4427fa7c">

# Settings

- [x] Please increase the default for `workspace.preloadFileSize`. Maybe `5120000`? 

- [x] `.emmyrc.json`: It'd be sweet to have a JSON schema. Then if you set "$schema" to the url users get config validation for free in VSCode. Are you intending to support `.laurc.json` as well? You're close enough to the [LuaLS .luarc.json schema](https://raw.githubusercontent.com/sumneko/vscode-lua/master/setting/schema.json) that I think you could implement proper superset of what it supports.

- [ ] `.emmyrc.json`: Please add support for `runtime.nonstandardSymbol`.  Here's what I use for Playdate Development: `["+=", "-=", "*=", "/=", "//=", "%=", "<<=", ">>=", "&=", "|=", "^="]`

# Future suggested capabilities

- [x] Add colors/tokenize type/names inside comment annotations.  `fun()`, `|` and `:` get fancy colorization, but everything else is just a comment (green).
    <img width="662" alt="Screenshot 2024-05-02 at 23 28 49" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/5f79f6b1-11db-465c-84aa-2c7bdee1024e">

- [ ] Analyzer should warn on duplicate assignments (unless inside `---@meta` file)
    <img width="143" alt="Screenshot 2024-05-02 at 22 42 11" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/d3d984a0-a85c-4abc-8c30-d68cf9feeb3c">

- [ ] Analyzer should warn when assigning incorrect types.
    <img width="164" alt="Screenshot 2024-05-02 at 22 38 35" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/61035294-964b-4cf6-a3b9-1bcc7ce99f93">

- [ ] Analyzer should warn/error when nullable types are not checked for nil before calling. E.g. `err:len()` should have warning. 
    <img width="337" alt="Screenshot 2024-05-02 at 21 59 49" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/d3b13593-3201-461e-a7be-91c893590ff2">

- [ ] Analyzer should warn when assigning to constants (this will fail at runtime)
    <img width="156" alt="Screenshot 2024-05-02 at 22 47 50" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/145113/31a95475-69b2-474f-b15c-47a37a3b6324">

----
Steps to reproduce:
1. Create a folder with an `.emmyrc.json`:
```json
{
    "workspace": {
        "preloadFileSize": 5120000,
        "library": [
            "../playdate-luacats"
        ]
    }
}
```
2. Checkout https://github.com/notpeter/playdate-luacats/ 
3. Profit?

**Comment by CppCXY** [comment]
good work, but there are some things that are not as you said. Emmylua does not define syntax highlighting, but instead uses the default highlighting of VScode, which is maintained by Sumneko. The reason you didn't see it is because it was overwritten by your other plugins

**Comment by notpeter** [comment]
Good work yourself! It's impressive to see this coming together.  Sorry to do such a big dump all at once.  I totally understand if some of these are by-design or out-of-scope, but I just wanted to share initial feedback of what I saw using the new LS for a couple hours. 

All the screenshots only have the EmmyLua and EmmyLuaCodeStyle extensions installed (I uninstalled Sumneko), but I had wrongly assumed that EmmyLuaVscode and EmmyLuaAnylzer were providing syntax highlighting and grammar definitions (via [DocumentSemanticTokensProvider](https://code.visualstudio.com/api/references/vscode-api#DocumentSemanticTokensProvider) or your own Grammar) but you are correct, this is just the default TextMate syntax highlighting, currently maintained by Sumneko.

Took me a minute to find it, but the main VSCode repo has [vscode/extensions/lua](https://github.com/microsoft/vscode/blob/main/extensions/lua/cgmanifest.json) which points to the [LuaLS/lua.tmbundle](https://github.com/LuaLS/lua.tmbundle) repo that I didn't know existed.  Thanks for pointing me in the direction of this.  I'll see if I can take a crack at a PR there which does some basic syntax highlighting of annotations (/me casually dusts off [oniguruma regex syntax manual](https://macromates.com/manual/en/regular_expressions#syntax_oniguruma))

Otherwise, enjoy your holiday. Excellent stuff.

**Comment by CppCXY** [comment]
By default, the highlighting in VSCode is like this, I don't know why it's not rendered on your computer:
![image](https://github.com/CppCXY/EmmyLuaAnalyzer/assets/40318218/54713d63-77bd-477b-acd6-805661653365)

You've asked many questions, and it's hard for me to respond to each one individually. I've turned some tasks into issues and responded within them. For other task questions, I'll give a general response:
1. Type checking is not currently implemented because type inference is not yet perfect. Also, many linters take time to develop (sumneko lua has been accumulating for several years, and many people submit PRs, I'm basically doing it alone, so it will be slower in terms of time).
2. The alias issue is how emmylua supported it in the past, but I've tried to be as compatible as possible with both syntaxes.
3. Regarding the compatibility with .luarc.json, I initially planned to directly use .luarc.json, but I found that many configurations are meaningless to my language service. So, I adopted a form that is basically consistent with it, but to avoid confusion, I didn't directly use .luarc.json, but used .emmyrc.json instead.

**Comment by notpeter** [comment]
Sounds great! I understand if there's certainly a difference in feature set vs LuaLS, but I'm very excited for there to be multiple players in the Lua Language Server space.  Your .NET code is definitely more accessible than LuaLS's mix of Lua and C++ spread across nearly a dozen repos.  I'm going to go ahead and close this issue, I created it mostly to document my first couple hours evaluating it and I thought you would appreciate the feedback.

Excited to see how things progress. In particular, hopefully you can get cross platform builds that don't require the CLR going as that will certainly ease adoption. I think this is part of the success of LuaLS -- it does not need to depend / interop with your target lua environment, everything is batteries-included when you add the extension.

Anyways, impressive work and I hope the feedback was useful.

**Comment by CppCXY** [comment]
Because it uses a lot of reflection libraries, it's currently not AOT-compilable. dotnet projects can be compiled in a self-contained manner, but the result of the compilation is to package the entire dotnet runtime, which will cause the package size to increase significantly, roughly from 6mb to 70mb. This is also not conducive to distribution. Initially, this project was written in Rust, and used a lot of libraries and ideas from rust-analyzer. However, at that time, Rust's debugging tools were too poor. After a few years, I see that C# has become very popular now, and various debugging tools are very complete. So I rewrote the project in C#.

**Comment by notpeter** [comment]
Gotcha. 70mb is a little chunky, but I don't think it's out of line.  Looking at my language servers:

| Server | Size |
|-|-|
| lua-language-server | 21MB |
| yaml-language-server | 29MB |
| pyright | 29MB |
| gopls | 31MB |
| typescript-language-server | 35MB |
| rust-analyzer | 39MB |
| vscode-css-language-server | 94MB |
| vscode-eslint | 108MB |

I'm not super familiar with the modern .NET ecosystem, but if it's possible (even if it includes the whole runtime) I'd suggest building a fat executable.  Developers on MacOS/Linux are unlikely to have a prexisting runtime installed and it's not immediately clear that what is needed is the runtime ([scroll down and look in the right-hand column](https://dotnet.microsoft.com/en-us/download/dotnet/8.0), 72MB) and not the SDK (front and center, 600MB).

You could support an automated install method (e.g. homebrew formula, chocolatey, etc) that installs the CLR as dependency but if you're targeting the widest possible audience I wouldn't worry about another 100MB.
