### ISSUE TITLE
全局变量分析问题

### ISSUE THREAD

**Issue by 37wjy** [CppCXY/EmmyLuaAnalyzer#20]
程序启动时会声明

```lua
---@type UIManager
UIMgr = require("UIManager").New()
```

在程序关闭时,会在特定方法里执行
```
UIMgr = nil
```

一旦写了后面的赋值代码后, 就会提示UIMgr是nil

<img width="322" alt="截屏2024-05-27 20 10 57" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/34015616/389636d6-f20b-404b-a0c8-3cb6e01646a8">

<img width="319" alt="截屏2024-05-27 20 10 47" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/34015616/3b1228f8-bd0c-402d-97ea-3f786e67e104">

**Comment by CppCXY** [comment]
这里面的主要问题是, lua的全局变量声明和赋值没有明显的区分, 当前采用的策略是,  以遍历顺序中的首次出现的类型为准

**Comment by 37wjy** [comment]
好吧, 主要是在上面标注了type, 要是提示 UIManager|nil 感觉也会比无视---@type会好点

**Comment by 37wjy** [comment]
有个比较特殊的情况, 有一些只会在特定情况下产生的local变量会被标记为全局变量, A前面的local去了就不会报错了

```
local DEBUG = true

if DEBUG then
    local A = {}
end

function B(...)
    if DEBUG then
        A.a = 1
    end
end

```


<img width="379" alt="截屏2024-06-06 11 22 48" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/34015616/15ddeeef-9d4e-461f-a8e3-b575f63b8795">

**Comment by CppCXY** [comment]
lua中不存在预处理器, 所以这个local 在通常情况下都是无法被访问的,  另一个办法是:
```lua
local DEBUG = true

if DEBUG then
    local A = {}
    function B(...)
        if DEBUG then
            A.a = 1
        end
    end
else
    function B(...)

    end
end
```
