### ISSUE TITLE
在table里不会提示bool变量

### ISSUE THREAD

**Issue by 37wjy** [CppCXY/EmmyLuaAnalyzer#26]
只有table里不会提示bool变量和function (...), 其他的变量和方法可以提示

<img width="442" alt="截屏2024-06-06 10 46 15" src="https://github.com/CppCXY/EmmyLuaAnalyzer/assets/34015616/b9f2b744-a1a7-4e8d-bad7-ba06ad6ab937">

**Comment by 37wjy** [comment]
有个小问题想问下, 有了`T` 的注释后可能会出现下面的情况

```lua
---@generic T : Car, K
---@param param1 `T`
---@param param2 K
---@return T
local function test(param1, param2) end

---@class Car
---@field a number
local car = {}

local value = test("Bus", car)
```

这个bus的class没有声明, 但是value可以提示为bus, 只是value里没有 .a 这个field的提示, 也不会认为bus是继承自car的, 这种情况是否应该认为bus继承car

**Comment by CppCXY** [comment]
这个表达是用来返回已知类型的, 而不是定义类型, 定义类型你依然需要使用`---@class Bus: car`
