### ISSUE TITLE
Document sync between Client and Server

### ISSUE THREAD

**Issue by deanmaster** [CppCXY/EmmyLuaAnalyzer#27]
Hello @CppCXY ,

i'm blocked to continue custom Language Server implementation. I used ReadHat LSP Client and using JSON Language Server from Microsoft.

I would like to archive that the content which I'm typing in my editor get sent and importantly updated to Documents manager which manages all text documents.

How do you implement the syncronization between LSP Client and LSP Server ? If we can't keep in sync all error shown and autocompletion keyword detection are wrong :(

Thanks a lot,
Tuan Do

**Comment by CppCXY** [comment]
When you type characters, the LSPClient sends the textDocument/didChange protocol to the server to update the document.

**Comment by deanmaster** [comment]
that's my problem I couldn't get this didChange event on my server. Currently, i have to dispatch the whole diagnostic to client which I do not want to. I would like to listen to this for every line and make the decision based on the line only not the whole document.

Either I code this
```
connection.onRequest(DidChangeTextDocumentNotification.method, (params: DidChangeTextDocumentParams, token: CancellationToken)
```
or this 
```
documents.onDidChangeContent((change)
```

None of them are working :(

**Comment by CppCXY** [comment]
Generally speaking, the language server needs to inform the client of its server capabilities about textdocument
