### ISSUE TITLE
字符串转义处理问题

### ISSUE THREAD

**Issue by tinymins** [CppCXY/EmmyLuaAnalyzer#32]
使用 GBK 编码保存以下LUA源码：

```lua
print("乗\")
```

然后运行：`lua.exe 1.lua`

![image](https://github.com/user-attachments/assets/283796af-c114-49ad-8803-235eee64a0d5)

此时 EmmyLua 提示语法错误，实际上没有语法错误

![image](https://github.com/user-attachments/assets/10163c0e-1b09-483a-b035-383bcf1a59bb)

似乎看起来很怪，但是LUA的特殊符号转义就是这么奇怪，按每个 byte 判断的转义，而乗的后半部分恰好是需要转义的字符，原理参照 https://zhaiyiming.com/archives/lua-string-bug-u4e57.html

py一种解决方式参照：

https://github.com/leafvmaple/luadata/blob/7c7b0918db45c4f194ef6cbddf62970b8b7c1392/luadata/serializer/serialize.py#L23
https://github.com/leafvmaple/luadata/blob/7c7b0918db45c4f194ef6cbddf62970b8b7c1392/luadata/serializer/unserialize.py#L170

**Comment by CppCXY** [comment]
不能处理这个问题, 因为实际上语言服务器内部用的UCS编码的字符串, 而不是基于特定编码的byte数组, 要基于特定编码做这个特殊处理, 影响分析效率

**Comment by tinymins** [comment]
感谢，我尝试使用 string.char 规避转义问题
