### ISSUE TITLE
0.8.10 之后，语言服务很大概率不提示注释信息、追踪定义位置不可用，插件仅显示基本语法高亮

### ISSUE THREAD

**Issue by tinymins** [CppCXY/EmmyLuaAnalyzer#34]
0.8.10 之后，语言服务很大概率不提示注释信息、追踪定义位置不可用，插件仅显示基本语法高亮。

当前版本 0.8.12

## 问题截图

正常应当鼠标指上去显示类型定义信息，现在不显示任何信息
![image](https://github.com/user-attachments/assets/8f3e6c76-c5fb-4b26-adf0-7770eeb4de9d)

F2重构提示 No result，无法重构变量名
![image](https://github.com/user-attachments/assets/e089a680-0ea8-4154-8629-7d6b1a3fd82a)
![image](https://github.com/user-attachments/assets/ad42f6fa-b0fc-4bfa-a71a-55c5fd58df94)

Extension Host 不显示 EmmyLua
![image](https://github.com/user-attachments/assets/dabe0c62-913d-462a-928d-89231a746467)

点击 EmmyLua 重启服务提示 exited with code 1
![image](https://github.com/user-attachments/assets/0155112c-d4cb-4627-a2a0-28ee456797a9)
![image](https://github.com/user-attachments/assets/450fa26a-4148-463a-bc28-7df4b150e419)
![image](https://github.com/user-attachments/assets/a4e5a9d9-c99e-465c-9004-39de708acee8)

错误提示信息正常显示
![image](https://github.com/user-attachments/assets/78bd721a-2e6e-4417-869e-2c57264e0325)

F2重命名变量甚至会错误识别变量名位置
![image](https://github.com/user-attachments/assets/a4729c28-6f00-44fa-b6d2-f153cf6d991c)

**Comment by tinymins** [comment]
测试库依然是 https://github.com/tinymins/JX3Boilerplate ，感谢

**Comment by tinymins** [comment]
重启几次 VSCode 后又恢复正常，不明白为什么

![image](https://github.com/user-attachments/assets/c44a86cd-18dd-4ba6-b7ed-450e68a3cad3)

**Comment by tinymins** [comment]
进展：

是否存在路径缓存之类的路径依赖？

实测在项目树文件夹结构中，语言服务不正常：
![image](https://github.com/user-attachments/assets/bbc000e3-eeaa-46f4-a6fd-c2ecc56957b6)

但是单独将项目与workspace文件移动到别处，语言服务正常：
![image](https://github.com/user-attachments/assets/6c1cc38f-12a4-48bc-9817-beeeace1869d)

**Comment by tinymins** [comment]
问题似乎已定位：项目路径不能携带空格

![image](https://github.com/user-attachments/assets/e95678a7-9283-4369-8f0a-f84cad6bb6b9)

**Comment by tinymins** [comment]
进展：matcher.GetResultsInFullPath(directory) 结果不包含 src/*.lua

![image](https://github.com/user-attachments/assets/92f6422d-b58c-4285-a205-9acc437136ae)

![image](https://github.com/user-attachments/assets/ea6a67e2-bb73-4dee-b195-8d4edf84a28c)

![image](https://github.com/user-attachments/assets/b75ed573-a5f6-4789-8e8e-7851b0ff8ebd)

**Comment by CppCXY** [comment]
原因是, document里面的uri不是解码过的

**Comment by CppCXY** [comment]
我已经修了, 你可以自己替换

**Comment by tinymins** [comment]
> 我已经修了, 你可以自己替换

感谢
