### ISSUE TITLE
关于动态注入对象中方法的emmy声明

### ISSUE THREAD

**Issue by UnableToCode** [CppCXY/EmmyLuaAnalyzer#38]
在0.6.18版本中，对于在不同文件中声明的
---@type XXX 
local mt = {}
 emmy是能把不同文件中定义的XXX的成员整合到一起的，
在文件A.lua中调用文件B.lua中的同为一个type XXX 的function能够实现补全和跳转
而在最新的0.8.20版本中似乎并不能这么做，这个是新增了配置项去控制吗？还是移除了这种使用type注解的方式？
这个对于习惯把模块拆分到多个lua文件中但是runtime时会注入到同一个对象中的情况来说会非常麻烦

**Comment by UnableToCode** [comment]
补充一点，在0.8.20中
在同一个文件中
如果用
---@type XXX
local mt = {}
声明类型，本文件中所有声明的mt中的成员自身也无法进行识别
eg.
声明
funtion mt:a()
end

再编写
function mt:b()
    self:a() -- 此处的a无法识别为上文定义的a函数
end

**Comment by CppCXY** [comment]
使用
```lua
---@class (partial) AA
```

`---@type xxx` 被视为只读, 不能在type的类型上定义新的字段

**Comment by UnableToCode** [comment]
好的，多谢解惑

**Comment by UnableToCode** [comment]
好像并不管用，emmy版本是0.8.20
![image](https://github.com/user-attachments/assets/68037f30-d0cb-4f71-b3cb-39c4a78ef6b0)

**Comment by CppCXY** [comment]
> 好像并不管用，emmy版本是0.8.20

需要robot的所有class声明都加上partial, 你参考C#就知道了

**Comment by UnableToCode** [comment]
解决了，多谢:)
